### PR TITLE
fix: use `dunce` crate to remove UNC prefix

### LINKED ISSUE #4: Support for Windows
Using `cargo-near` on Windows results in these errors:
```
error: couldn't read \\?\C:\Users\diteg\Work\near-sdk-rs\examples\abi\target\near\abi-near-abi-gen\target\release\build\crunchy-35e8e00adbbf080a\out/lib.rs: The filename, directory name, or volume label syntax is incorrect. (os error 123)
  --> C:\Users\diteg\.cargo\registry\src\github.com-1ecc6299db9ec823\crunchy-0.2.2\src\lib.rs:36:1
   |
36 | include!(concat!(env!("OUT_DIR"), "/lib.rs"));
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `include` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `crunchy` due to previous error
warning: build failed, waiting for other jobs to finish...
error: couldn't read \\?\C:\Users\diteg\Work\near-sdk-rs\examples\abi\target\near\abi-near-abi-gen\target\release\build\rustversion-19b9a7e40293d578\out/version.expr: The filename, directory name, or volume label syntax is incorrect. (os error 123)
   --> C:\Users\diteg\.cargo\registry\src\github.com-1ecc6299db9ec823\rustversion-1.0.7\src\lib.rs:185:30
    |
185 | const RUSTVERSION: Version = include!(concat!(env!("OUT_DIR"), "/version.expr"));
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `include` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `rustversion` due to previous error
error: couldn't read \\?\C:\Users\diteg\Work\near-sdk-rs\examples\abi\target\near\abi-near-abi-gen\target\release\build\reed-solomon-erasure-72d98e9b864bbed5\out/table.rs: The filename, directory name, or volume label syntax is incorrect. (os error 123)
 --> C:\Users\diteg\.cargo\registry\src\github.com-1ecc6299db9ec823\reed-solomon-erasure-4.0.2\src\galois_8.rs:3:1
  |
3 | include!(concat!(env!("OUT_DIR"), "/table.rs"));
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `include` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `reed-solomon-erasure` due to previous error
ERROR: `"\\\\?\\C:\\Users\\diteg\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\bin\\cargo.exe" "run" "--package" "near-abi-gen" "--release"` failed with exit code: Some(101)
```

The dependency are coming from near-sdk-rs and are presumably uncompilable on Windows due to Unix paths. That being said, if I open PowerShell and manually go to the directory I can compile the generated project just fine. (tested with stable-mscv)

### PR DESCRIPTION
**Pull request by iho**
Closes #4 

On Windows, `Path::canonicalize()` returns a path with the UNC prefix not supported by `cmd.exe` and breaks the compilation of all crates that have `include!` macros in it. The problem is well known, and no proper solution at the current moment https://github.com/rust-lang/rust/issues/42869 
For now, I just cut this UNC prefix, but if users complain about that, we can come out with a more sophisticated solution like https://lib.rs/crates/dunce

### CODE REVIEW

File: cargo-near/src/util/mod.rs [hunk 1]
```diff
@@ -241,8 +243,14 @@ pub(crate) fn compile_project(
...
-    dir.canonicalize_utf8()
-        .wrap_err_with(|| format!("failed to access output directory `{}`", dir))
+    // use canonicalize from `dunce` create instead of default one from std because it's compatible with Windows UNC paths
+    // and don't breake cargo compilation on Windows
+    // https://github.com/rust-lang/rust/issues/42869
+    let compatible_path = dunce::canonicalize(dir);
+    match compatible_path {
+        Ok(path) => Ok(Utf8PathBuf::from_path_buf(path).unwrap()),
+        Err(err) => Err(err).wrap_err_with(|| format!("failed to canonicalize path: {} ", dir)),
+    }
```
Comment (frol) [inline cargo-near/src/util/mod.rs:253]: We should not unwrap, so handle the error gracefully, and you shouldn't need to match explicitly, instead, use `?` operator:

```suggestion
    Utf8PathBuf::from_path_buf(
        dunce::canonicalize(dir)
            .wrap_err_with(|| format!("failed to canonicalize path: {} ", dir))?
    )
    .wrap_err_with(|| format!("failed to convert canonicalized path to UTF-8 path: {} ", dir))
    .into()
```

File: cargo-near/src/util/mod.rs [hunk 2]
```diff
@@ -241,8 +243,14 @@ pub(crate) fn compile_project(
 /// Create the directory if it doesn't exist, and return the absolute path to it.
 pub(crate) fn force_canonicalize_dir(dir: &Utf8Path) -> color_eyre::eyre::Result<Utf8PathBuf> {
     fs::create_dir_all(dir).wrap_err_with(|| format!("failed to create directory `{}`", dir))?;
-    dir.canonicalize_utf8()
-        .wrap_err_with(|| format!("failed to access output directory `{}`", dir))
+    // use canonicalize from `dunce` create instead of default one from std because it's compatible with Windows UNC paths
+    // and don't breake cargo compilation on Windows
```
Comment (frol) [inline cargo-near/src/util/mod.rs:247]:
```suggestion
    // and don't break cargo compilation on Windows
```

File: cargo-near/src/util/mod.rs [hunk 3]
```diff
@@ -241,8 +243,14 @@ pub(crate) fn compile_project(
...
+    // https://github.com/rust-lang/rust/issues/42869
+    Utf8PathBuf::from_path_buf(
+        dunce::canonicalize(dir)
+            .wrap_err_with(|| format!("failed to canonicalize path: {} ", dir))?,
+    )
+    .map_err(|err| color_eyre::eyre::eyre!(" failed to convert path {}", err.to_string_lossy()))
```
Comment (frol) [inline cargo-near/src/util/mod.rs:253]:
```suggestion
    .map_err(|err| color_eyre::eyre::eyre!("failed to convert path {}", err.to_string_lossy()))
```

File: cargo-near/src/util/mod.rs [hunk 4]
```diff
@@ -56,6 +56,8 @@ where
 
     if let Some(path) = working_dir {
         let path = path.as_ref();
+        // remove UNC prefix to be able to compile on Windows
+        let path = force_canonicalize_dir(path)?;
```
Comment (frol) [inline cargo-near/src/util/mod.rs:60]:
```suggestion
        let path = force_canonicalize_dir(path.as_ref())?;
```

**Review by frol — CHANGES_REQUESTED** [review]
